# railway.toml
[build]
builder = "dockerfile"
dockerfilePath = "./HNG-Task2/Dockerfile"
[build]
builder = "NIXPACKS"
buildCommand = "dotnet publish -c Release -o out"

[start]

startCommand = "dotnet out/HNG_Task2.dll"

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://+:8080"
PORT = "8080"
