[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "dotnet out/HNG-Task2.dll"

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"
PORT = "8080"
Storage__JsonFilePath = "/tmp/strings.json"
