# railway.toml
[build]
# This tells Railway how to build your project
builder = "NIXPACKS"
buildCommand = "dotnet publish -c Release -o out"

[deploy]
# This tells Railway how to start your API
startCommand = "dotnet out/HNG_Task2.dll"
"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
# These are your environment variables (set in Railway Dashboard)
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://+:8080"
PORT = "8080"
