[build]
builder = "NIXPACKS"
buildCommand = "dotnet clean && dotnet publish HNG-Task2/HNG-Task2.csproj -c Release -o out && ls -l out/"

[deploy]
startCommand = "dotnet out/HNG_Task2.dll"

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"
PORT = "8080"
Storage__JsonFilePath = "/tmp/strings.json"
NIXPACKS_CSHARP_SDK_VERSION = "8.0"